gzip_static on;
gzip_vary on;

map_hash_max_size 1024;
map_hash_bucket_size 1024;

map $uri $kit10_route_file {
	default /__kit10_not_found__;

	# MARK: routes
}

map $kit10_route_file $kit10_link_header {
	default "";

	# MARK: link headers
}
