listen 3000;

root /var/www/kit10;

location / {
	add_header Link $kit10_link_header;

	try_files $uri
	          $uri+page.html
	          $uri/index+page.html
	          $kit10_route_file
	          =404;
}
